# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-imap-adapter}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Herald"]
  s.date = %q{2009-10-20}
  s.description = %q{DataMapper IMAP adapter}
  s.email = %q{nathan@myobie.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "dm-imap-adapter.gemspec",
     "lib/dm-imap-adapter.rb",
     "lib/dm-imap-adapter/net_imap_ext.rb",
     "lib/dm-imap-adapter/types.rb",
     "spec/.bacon",
     "spec/dm-imap-adapter_spec.rb",
     "spec/spec_helper.rb",
     "spec/watchr.rb"
  ]
  s.homepage = %q{http://github.com/myobie/dm-imap-adapter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An IMAP adapter for DM}
  s.test_files = [
    "spec/dm-imap-adapter_spec.rb",
     "spec/spec_helper.rb",
     "spec/watchr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

